name: Build and Deploy
on:
    push:
        branches:
            - main
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

env:
    CI: true
    REGISTRY: 'harbor.blackpaws.fr'
    PROJECT: 'production'
    NAMESPACE: 'blackpaws'


jobs:
    build-and-deploy-docker-image:
        runs-on: ubuntu-latest
        outputs:
            IMAGE_TAG: ${{ steps.create-image-tag.outputs.IMAGE_TAG }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Login to Harbor
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ secrets.HARBOR_USERNAME  }}
                  password: ${{ secrets.HARBOR_PASSWORD }}
            - name: Create image tag
              id: create-image-tag
              run: |
                  echo "IMAGE_TAG=$(echo -n ${{ github.sha }} | cut -c 1-7)" >> "$GITHUB_OUTPUT"
            - name: Next.js Build and push docker image
              run: |
                  docker buildx build --platform linux/amd64 -f Dockerfile -t ${{ env.REGISTRY }}/${{ env.PROJECT }}/${{ env.NAMESPACE }}:${{ steps.create-image-tag.outputs.IMAGE_TAG }} .
                  docker push ${{ env.REGISTRY }}/${{ env.PROJECT }}/${{ env.NAMESPACE }}:${{ steps.create-image-tag.outputs.IMAGE_TAG }}
    deploy-blackpaws:
        runs-on: [self-hosted, macOS]
        needs: build-and-deploy-docker-image
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
                  repository: "blackfoot-makers/deployments"
            - name: Deploy blackpaws
              run: |
                  kubectl -n ${{ env.NAMESPACE }} set image deployment/blackpaws blackpaws=${{ env.REGISTRY }}/${{ env.PROJECT }}/${{ env.NAMESPACE }}:${{ needs.build-and-deploy-docker-image.outputs.IMAGE_TAG }}
                  kubectl -n ${{ env.NAMESPACE }} rollout status deployment/blackpaws
                  kubectl -n ${{ env.NAMESPACE }} get service blackpaws
